###
POST http://localhost:3015/auth/signin
Content-Type: application/json

{
    "username":"vomann",
    "password":"vomann"
}

###
POST http://localhost:3015/auth/login
Content-Type: application/json

{
    "email":"tvomann2121@gmail.com"
}


###

POST http://localhost:3015/auth/verify-otp
Content-Type: application/json

{
    "email":"nagasainithin37@gmail.com",
    "otp":"592045"
}