

###
POST http://localhost:3015/auth/login
Content-Type: application/json

{
    "email":"tvomann2121@gmail.com"
}


###

POST http://localhost:3015/auth/verify-otp
Content-Type: application/json

{
    "email":"tvomann2121@gmail.com",
    "otp":"664820"
}


###
GET http://localhost:3015/booking/get-empty-slots?date=28-8-2023


###
POST http://localhost:3015/booking/book-slot
Content-Type: application/json

{
    "date":"28-8-2023",
    "slotIdx":3,
    "email":"tvomann2121@gmail.com"
}


###
POST http://localhost:3015/booking/cancel-booking
Content-Type: application/json

{
    "date":"28-8-2023",
    "slotIdx":3,
    "email":"tvomann2121@gmail.com"
}